name: "è‡ªåŠ¨ç®¡ç†è¿‡æ—¶çš„é—®é¢˜å’ŒPR"
on:
  schedule:
    - cron: "0 18 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: |
            âš ï¸ æ­¤ Issue å·²è¶…è¿‡ä¸€å®šæ—¶é—´æœªæ´»åŠ¨ï¼Œå¦‚æœæ²¡æœ‰è¿›ä¸€æ­¥æ›´æ–°ï¼Œå°†åœ¨ 30 å¤©åå…³é—­ã€‚
          close-issue-message: |
            ğŸ”’ ç”±äºé•¿æ—¶é—´æœªå“åº”ï¼Œæ­¤ Issue å·²è¢«è‡ªåŠ¨å…³é—­ã€‚å¦‚æœ‰éœ€è¦ï¼Œè¯·é‡æ–°æ‰“å¼€æˆ–æäº¤æ–° issueã€‚
          stale-pr-message: |
            âš ï¸ æ­¤ PR å·²è¶…è¿‡ä¸€å®šæ—¶é—´æœªæ›´æ–°ï¼Œè¯·æ›´æ–°ï¼Œå¦åˆ™å°†åœ¨ 30 å¤©åå…³é—­ã€‚
          close-pr-message: |
            ğŸ”’ æ­¤ PR å·²å› æ— æ›´æ–°è€Œè‡ªåŠ¨å…³é—­ã€‚å¦‚ä»éœ€åˆå¹¶ï¼Œè¯·é‡æ–°æ‰“å¼€æˆ–æäº¤æ–° PRã€‚

          days-before-issue-stale: 60
          days-before-pr-stale: 60
          days-before-close: 30

          stale-issue-label: "æœªè·Ÿè¿›é—®é¢˜(Stale)"
          close-issue-label: "è‡ªåŠ¨å…³é—­(Close)"
          stale-pr-label: "æœªè·Ÿè¿›é—®é¢˜(Stale)"
          close-pr-label: "è‡ªåŠ¨å…³é—­(Close)"
          exempt-issue-labels: "æ–°åŠŸèƒ½(feature),åŠŸèƒ½å¼‚å¸¸(bug),æ–‡æ¡£è¡¥å……(docs),åŠŸèƒ½ä¼˜åŒ–(enhancement),é€‚åˆæ–°æ‰‹(good first issue),"
          exempt-pr-labels: "æ–°åŠŸèƒ½(feature),åŠŸèƒ½å¼‚å¸¸(bug),æ–‡æ¡£è¡¥å……(docs),åŠŸèƒ½ä¼˜åŒ–(enhancement),é€‚åˆæ–°æ‰‹(good first issue),"
