name: "è‡ªåŠ¨ç®¡ç†è¿‡æ—¶çš„é—®é¢˜å’ŒPR"
on:
  schedule:
    - cron: "0 0 */4 * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: |
            âš ï¸ æ­¤ Issue å·²è¶…è¿‡ä¸€å®šæ—¶é—´æœªæ´»åŠ¨ï¼Œå¦‚æœæ²¡æœ‰è¿›ä¸€æ­¥æ›´æ–°ï¼Œå°†åœ¨ 14 å¤©åå…³é—­ã€‚
            âš ï¸ This issue has been inactive for a certain period of time. If there are no further updates, it will be closed in 14 days.
          close-issue-message: |
            ğŸ”’ ç”±äºé•¿æ—¶é—´æœªå“åº”ï¼Œæ­¤ Issue å·²è¢«è‡ªåŠ¨å…³é—­ã€‚å¦‚æœ‰éœ€è¦ï¼Œè¯·é‡æ–°æ‰“å¼€æˆ–æäº¤æ–° issueã€‚
            ğŸ”’ Due to prolonged inactivity, this issue has been automatically closed. If needed, please reopen it or submit a new issue.
          stale-pr-message: |
            âš ï¸ æ­¤ PR å·²è¶…è¿‡ä¸€å®šæ—¶é—´æœªæ›´æ–°ï¼Œè¯·æ›´æ–°ï¼Œå¦åˆ™å°†åœ¨ 14 å¤©åå…³é—­ã€‚
            âš ï¸ This PR has not been updated for a certain period of time. Please update it, otherwise it will be closed in 14 days.
          close-pr-message: |
            ğŸ”’ æ­¤ PR å·²å› æ— æ›´æ–°è€Œè‡ªåŠ¨å…³é—­ã€‚å¦‚ä»éœ€åˆå¹¶ï¼Œè¯·é‡æ–°æ‰“å¼€æˆ–æäº¤æ–° PRã€‚
            ğŸ”’ This PR has been automatically closed due to inactivity. If you still wish to merge it, please reopen it or submit a new PR.

          days-before-stale: 28
          days-before-close: 14

          ascending: true

          stale-issue-label: "æœªè·Ÿè¿›é—®é¢˜(Stale)"
          close-issue-label: "è‡ªåŠ¨å…³é—­(Close)"
          stale-pr-label: "æœªè·Ÿè¿›é—®é¢˜(Stale)"
          close-pr-label: "è‡ªåŠ¨å…³é—­(Close)"
          exempt-issue-labels: "åŠŸèƒ½å¼‚å¸¸(bug),æ–‡æ¡£è¡¥å……(docs),åŠŸèƒ½ä¼˜åŒ–(enhancement),é€‚åˆæ–°æ‰‹(good first issue),"
          exempt-pr-labels: "åŠŸèƒ½å¼‚å¸¸(bug),æ–‡æ¡£è¡¥å……(docs),åŠŸèƒ½ä¼˜åŒ–(enhancement),é€‚åˆæ–°æ‰‹(good first issue),"
